services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: laravel_app
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3307
      - DB_DATABASE=rr_back
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8181:8181"
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: rr_back
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3307"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
